### PR TITLE
Fix 9313 universal abbr

### PR DESCRIPTION
**Pull request by hgibs**
Fixes two issues:

1. Upstream [issue 9313 ](https://github.com/fish-shell/fish-shell/pull/9313) changes how abbreviations work. They are no longer universal and need to get loaded on every interactive prompt (but also they are much faster so it doesn't matter as much). This fix loads in these abbreviations on every call to `__kubectl.init`

2. fisher installations without oh-my-fish (like mine) don't call anything in the `hooks` directory. So these abbreviations aren't loaded on subsequent new shells. Triggering `_kubectl_init` on interactive prompts fixes this.

I am running this current config on my installation and seems to work as intended.

### CODE REVIEW

**Comment by hgibs** [comment]
@blackjid Can you take a look at this?

I changed a few things, incorporating some lessons learned from the same issue on the git-plugin. The unpatched plugin on `master` doesn't work at all on fish ~6.3.0~ 3.6.0+

**Comment by blackjid** [comment]
hey, sorry, I didn't got the first message.., let me test it and i'll get back to you..

**Comment by blackjid** [comment]
> doesn't work at all on fish 6.3.0+

do you mean fish 3.6.0+?

**Comment by hgibs** [comment]
lol yes, oops

**Pull request merged**
